# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-10 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15)),
                ('nome', models.TextField()),
                ('idade', models.IntegerField()),
                ('telefone', models.TextField()),
                ('endereco', models.TextField()),
            ],
        ),
    ]
