# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-10 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0004_auto_20171110_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.TextField()),
                ('graduacao', models.TextField()),
                ('academia_Associada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fed_judo.Usuario')),
            ],
        ),
    ]
