# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-10 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0005_atleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.IntegerField()),
                ('salario', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='atleta',
            name='academia_Associada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fed_judo.Academia'),
        ),
    ]
