# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-10 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_academia', models.IntegerField()),
                ('nome_Academia', models.TextField()),
                ('enredeco_academia', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='Usuario',
        ),
    ]
