# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-10 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0006_auto_20171110_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.TextField()),
                ('funcao', models.TextField()),
            ],
        ),
    ]
