# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0007_juiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
