# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0008_auto_20171111_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.IntegerField(max_length=15, null=True, unique=True),
        ),
    ]
