# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0010_auto_20171111_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.TextField()),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('premiacao', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
