# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-14 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0011_auto_20171112_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaleConosco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('email', models.TextField()),
                ('mensagem', models.TextField()),
                ('hora_envio', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
