# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-20 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0013_auto_20171120_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='limite_atletas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
