# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-20 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0015_auto_20171120_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='juiz',
            name='qualquer',
            field=models.IntegerField(null=True),
        ),
    ]
