# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-20 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0016_juiz_qualquer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juiz',
            name='qualquer',
        ),
    ]
