# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-22 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0017_remove_juiz_qualquer'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='telefone',
            field=models.IntegerField(null=True),
        ),
    ]
