# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-22 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0018_academia_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='email',
            field=models.EmailField(max_length=75, null=True),
        ),
    ]
