# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-22 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0019_academia_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='pontuacao',
            field=models.IntegerField(null=True),
        ),
    ]
