# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-22 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0020_academia_pontuacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academia',
            name='pontuacao',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
