# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-22 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0021_auto_20171122_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('corpo', models.TextField()),
                ('imagem', models.ImageField(upload_to='noticias')),
            ],
        ),
    ]
