# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-23 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0023_noticia_data_lancamento_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fed_judo.Usuario'),
        ),
    ]
