# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0023_noticia_data_lancamento_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
