# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fed_judo', '0024_auto_20171123_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='login',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
