# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-23 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0024_noticia_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
