# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-23 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0025_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.TextField(blank=True),
        ),
    ]
