# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-23 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0026_auto_20171123_1806'),
        ('fed_judo', '0025_usuario_login'),
    ]

    operations = [
    ]
